spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_post_storage
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
